### ISSUE TITLE
给up主的一些个人建议

### ISSUE THREAD

**Issue by xiyanxiyan10** [ideascf/octopus#2]
1.代码使用中文说明，github上外国人很多,且能避免文本编码问题
2.快速开始文档，产品定位说明，性能测试报告等可以让其他人快速看懂和确认是否使用该工程.

**Comment by ideascf** [comment]
1. 目前为自主开发阶段，当雏形完成时会对注释以及文档进行翻译
2. octopus不是一个高频的模块，只会在集群状态发生改变以及心跳时才会使用cpu。
3. 产品定位就是：一个**python**的**分布式**协调**框架**，解决`名称服务`、`配置共享`、`master选举`这三个在集群环境中常见的问题。

**Comment by xiyanxiyan10** [comment]
I got it, Thank you!
